networks:
  roomx_network:
    name: roomx_network
    external: true

services:
  roomx-fe:
    image: roomx-fe:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["bun", "run", "preview", "--host", "0.0.0.0", "--port", "4173"]
    restart: always
    networks:
      - roomx_network