networks:
  roomx_network:
    name: roomx_network
    external: true

services:
  roomx-fe:
    image: node:lts
    container_name: roomx-fe
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    restart: always
    networks:
      - roomx_network
