networks:
  roomx_network:
    name: roomx_network
    external: true

volumes:
  app_data:
  node_modules:

services:
  roomx-fe:
    image: roomx-fe:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - app_data:/app
      - node_modules:/app/node_modules
    command: ["bun", "run", "preview", "--host", "0.0.0.0", "--port", "4173"]
    restart: always
    networks:
      - roomx_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
    user: node