pipeline {
    agent any
    environment {
        REPO_URL = 'https://github.com/JiaG293/test-fe.git'
        WORKDIR = 'dev-fe-web'
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: REPO_URL
            }
        }

        stage('Load ENV File') {
            steps {
                withCredentials([file(credentialsId: 'roomx-fe-dev-env', variable: 'ENV_FILE')]) {
                    sh '''
                        set -x
                        chmod 644 $ENV_FILE
                        rm -f $WORKDIR/.env
                        cp $ENV_FILE $WORKDIR/.env
                        ls -la $WORKDIR/
                    '''
                }
            }
        }

        stage('Build & Deploy Docker Image') {
            steps {
                script {
                    sh '''
                        cd $WORKDIR
                        docker image prune -af || true
                        docker compose up -d --force-recreate roomx-fe
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
